name: CorePlugin
version: ${project.version}
main: net.lowmc.core.CorePlugin
api-version: 1.13
authors: [Piechuuu, Sklejuwa]
description: Core lowmc.pl
website: www.lowmc.pl

commands:
  vip:
    description: Po wpisaniu ukazuja sie informacje na temat rangi vip
